from cudaTestProgram import * 

raceyTests = [
    CudaRaceTestProgram("racey/atomic_increment.cu",
        macros={'GLOBAL':None,'BLOCKS':'1','THREADS':'2'},
        testCases=[ 
            CudaTestCase(CudaError.NO_RACE),
        ]),
    CudaRaceTestProgram("racey/atomic_increment.cu",
        macros={'SHARED':None,'BLOCKS':'1','THREADS':'2'},
        testCases=[ 
            CudaTestCase(CudaError.NO_RACE),
        ]),
    CudaRaceTestProgram("racey/atomic_increment.cu",
        macros={'GLOBAL':None,'BLOCKS':'1','THREADS':'3'},
        testCases=[ 
            CudaTestCase(CudaError.NO_RACE),
        ]),
    CudaRaceTestProgram("racey/atomic_increment.cu",
        macros={'SHARED':None,'BLOCKS':'1','THREADS':'33'},
        testCases=[ 
            CudaTestCase(CudaError.NO_RACE),
        ]),
    CudaRaceTestProgram("racey/atomic_increment.cu",
        macros={'GLOBAL':None,'BLOCKS':'2','THREADS':'1'},
        testCases=[ 
            CudaTestCase(CudaError.NO_RACE),
        ]),
    CudaRaceTestProgram("racey/atomic_increment.cu",
        macros={'SHARED':None,'BLOCKS':'2','THREADS':'1'},
        testCases=[ 
            CudaTestCase(CudaError.NO_RACE),
        ]),
    CudaRaceTestProgram("racey/base.cu",
        macros={'GLOBAL':None,'RW':None,'BLOCKS':'1','THREADS':'2'},
        testCases=[ 
            CudaTestCase([CudaError.GLB_WAR,CudaError.GLB_WAW]),
        ]),
    CudaRaceTestProgram("racey/base.cu",
        macros={'GLOBAL':None,'WW': None,'BLOCKS':'1','THREADS':'2'},
        testCases=[ 
            CudaTestCase(CudaError.GLB_WAW),
        ]),
    CudaRaceTestProgram("racey/base.cu",
        macros={'SHARED':None,'RW':None,'BLOCKS':'1','THREADS':'2'},
        testCases=[ 
            CudaTestCase([CudaError.SHR_WAR,CudaError.SHR_WAW]),
        ]),
    CudaRaceTestProgram("racey/base.cu",
        macros={'SHARED':None,'WW': None,'BLOCKS':'1','THREADS':'2'},
        testCases=[ 
            CudaTestCase(CudaError.SHR_WAW),
        ]),
    CudaRaceTestProgram("racey/base.cu",
        macros={'GLOBAL':None,'RW':None,'BLOCKS':'1','THREADS':'33'},
        testCases=[ 
            CudaTestCase([CudaError.GLB_WAR,CudaError.GLB_WAW]),
        ]),
    CudaRaceTestProgram("racey/base.cu",
        macros={'GLOBAL':None,'WW': None,'BLOCKS':'1','THREADS':'33'},
        testCases=[ 
            CudaTestCase(CudaError.GLB_WAW),
        ]),
    CudaRaceTestProgram("racey/base.cu",
        macros={'SHARED':None,'RW':None,'BLOCKS':'1','THREADS':'33'},
        testCases=[ 
            CudaTestCase([CudaError.SHR_RAW,CudaError.SHR_WAR,CudaError.SHR_WAW]),
        ]),
    CudaRaceTestProgram("racey/base.cu",
        macros={'SHARED':None,'WW': None,'BLOCKS':'1','THREADS':'33'},
        testCases=[ 
            CudaTestCase(CudaError.SHR_WAW),
        ]),
    CudaRaceTestProgram("racey/base.cu",
        macros={'GLOBAL':None,'RW':None,'BLOCKS':'2','THREADS':'1'},
        testCases=[ 
            CudaTestCase([CudaError.GLB_WAR,CudaError.GLB_WAW]),
        ]),
    CudaRaceTestProgram("racey/base.cu",
        macros={'GLOBAL':None,'WW': None,'BLOCKS':'2','THREADS':'1'},
        testCases=[ 
            CudaTestCase(CudaError.GLB_WAW),
        ]),
    CudaRaceTestProgram("racey/base_with_syncthreads.cu",
        macros={'GLOBAL':None,'RW':None,'BLOCKS':'1','THREADS':'33'},
        testCases=[ 
            CudaTestCase(CudaError.NO_RACE),
        ]),
    CudaRaceTestProgram("racey/base_with_syncthreads.cu",
        macros={'GLOBAL':None,'WW': None,'BLOCKS':'1','THREADS':'33'},
        testCases=[ 
            CudaTestCase(CudaError.NO_RACE),
        ]),
    CudaRaceTestProgram("racey/base_with_syncthreads.cu",
        macros={'SHARED':None,'RW':None,'BLOCKS':'1','THREADS':'33'},
        testCases=[ 
            CudaTestCase(CudaError.NO_RACE),
        ]),
    CudaRaceTestProgram("racey/base_with_syncthreads.cu",
        macros={'SHARED':None,'WW': None,'BLOCKS':'1','THREADS':'33'},
        testCases=[ 
            CudaTestCase(CudaError.NO_RACE),
        ]),
    CudaRaceTestProgram("racey/base_with_syncthreads.cu",
        macros={'GLOBAL':None,'RW':None,'BLOCKS':'2','THREADS':'1'},
        testCases=[ 
            CudaTestCase([CudaError.GLB_WAR,CudaError.GLB_WAW]),
        ]),
    CudaRaceTestProgram("racey/base_with_syncthreads.cu",
        macros={'GLOBAL':None,'WW': None,'BLOCKS':'2','THREADS':'1'},
        testCases=[ 
            CudaTestCase(CudaError.GLB_WAW),
        ]),
    CudaRaceTestProgram("racey/branch_race.cu",
        macros={'GLOBAL':None,'BLOCKS':'1','THREADS':'2'},
        testCases=[ 
            CudaTestCase(CudaError.GLB_WAR),
        ]),
    CudaRaceTestProgram("racey/branch_race.cu",
        macros={'SHARED':None,'BLOCKS':'1','THREADS':'2'},
        testCases=[ 
            CudaTestCase(CudaError.SHR_WAR),
        ]),
    CudaRaceTestProgram("racey/dynamic_parallelism.cu",
        macros={'RW':None},
        testCases=[ 
            CudaTestCase([CudaError.GLB_RAW,CudaError.GLB_WAR]),
        ]),
    CudaRaceTestProgram("racey/dynamic_parallelism.cu",
        macros={'WW':None},
        testCases=[ 
            CudaTestCase(CudaError.GLB_WAW),
        ]),
    CudaRaceTestProgram("racey/dynamic_parallelism.cu",
        macros={'RW':None,'PARENT_LEADS':None},
        testCases=[ 
            CudaTestCase(CudaError.NO_RACE),
        ]),
    CudaRaceTestProgram("racey/dynamic_parallelism.cu",
        macros={'WW':None,'PARENT_LEADS':None},
        testCases=[ 
            CudaTestCase(CudaError.NO_RACE),
        ]),
    CudaRaceTestProgram("racey/dynamic_parallelism.cu",
        macros={'RW':None,'PARENT_WAITS':None},
        testCases=[ 
            CudaTestCase(CudaError.NO_RACE),
        ]),
    CudaRaceTestProgram("racey/dynamic_parallelism.cu",
        macros={'WW':None,'PARENT_WAITS':None},
        testCases=[ 
            CudaTestCase(CudaError.NO_RACE),
        ]),
    CudaRaceTestProgram("racey/dynamic_parallelism_with_streams.cu",
        macros={'RW':None},
        testCases=[ 
            CudaTestCase([CudaError.GLB_RAW,CudaError.GLB_WAR]),
        ]),
    CudaRaceTestProgram("racey/dynamic_parallelism_with_streams.cu",
        macros={'WW':None},
        testCases=[ 
            CudaTestCase(CudaError.GLB_WAW),
        ]),
    CudaRaceTestProgram("racey/dynamic_parallelism_with_streams.cu",
        macros={'RW':None,'DEVICE_SYNC':None},
        testCases=[ 
            CudaTestCase(CudaError.NO_RACE),
        ]),
    CudaRaceTestProgram("racey/dynamic_parallelism_with_streams.cu",
        macros={'WW':None,'DEVICE_SYNC':None},
        testCases=[ 
            CudaTestCase(CudaError.NO_RACE),
        ]),
    CudaRaceTestProgram("racey/dynamic_parallelism_with_streams.cu",
        macros={'RW':None,'EVENT_SYNC':None},
        testCases=[ 
            CudaTestCase(CudaError.NO_RACE),
        ]),
    CudaRaceTestProgram("racey/dynamic_parallelism_with_streams.cu",
        macros={'WW':None,'EVENT_SYNC':None},
        testCases=[ 
            CudaTestCase(CudaError.NO_RACE),
        ]),
    CudaRaceTestProgram("racey/dynamic_parallelism_with_streams.cu",
        macros={'RW':None,'STREAM_EVENT_SYNC':None},
        testCases=[ 
            CudaTestCase(CudaError.NO_RACE),
        ]),
    CudaRaceTestProgram("racey/dynamic_parallelism_with_streams.cu",
        macros={'WW':None,'STREAM_EVENT_SYNC':None},
        testCases=[ 
            CudaTestCase(CudaError.NO_RACE),
        ]),
    CudaRaceTestProgram("racey/dynamic_parallelism_with_streams.cu",
        macros={'RW':None,'STREAM_EVENT_SYNC_NOOP':None},
        testCases=[ 
            CudaTestCase([CudaError.GLB_RAW,CudaError.GLB_WAR]),
        ]),
    CudaRaceTestProgram("racey/dynamic_parallelism_with_streams.cu",
        macros={'WW':None,'STREAM_EVENT_SYNC_NOOP':None},
        testCases=[ 
            CudaTestCase(CudaError.GLB_WAW),
        ]),
    CudaRaceTestProgram("racey/flag_sync_across_blocks.cu",
        testCases=[ 
            CudaTestCase(CudaError.NO_RACE),
        ]),
    CudaRaceTestProgram("racey/flag_sync_across_blocks.cu",
        macros={'ATOMIC':None},
        testCases=[ 
            CudaTestCase(CudaError.NO_RACE),
        ]),
    CudaRaceTestProgram("racey/flag_sync_across_blocks.cu",
        macros={'ATOMIC':None,'NO_VOLATILE':None},
        testCases=[ 
            CudaTestCase(CudaError.NO_RACE),
        ]),
    CudaRaceTestProgram("racey/flag_sync_across_blocks.cu",
        macros={'NO_VOLATILE':None,'PTX_CA':None},
        testCases=[ 
            CudaTestCase(CudaError.GLB_RAW),
        ]),
    CudaRaceTestProgram("racey/flag_sync_across_blocks.cu",
        macros={'NO_VOLATILE':None,'PTX_CG':None},
        testCases=[ 
            CudaTestCase(CudaError.NO_RACE),
        ]),
    CudaRaceTestProgram("racey/implicit_intra_warp_sync.cu",
        macros={'GLOBAL':None,'RW': None,'BLOCKS':'1','THREADS':'2'},
        testCases=[ 
            CudaTestCase(CudaError.NO_RACE),
        ]),
    CudaRaceTestProgram("racey/implicit_intra_warp_sync.cu",
        macros={'GLOBAL':None,'WW': None,'BLOCKS':'1','THREADS':'2'},
        testCases=[ 
            CudaTestCase(CudaError.NO_RACE),
        ]),
    CudaRaceTestProgram("racey/implicit_intra_warp_sync.cu",
        macros={'SHARED':None,'RW': None,'BLOCKS':'1','THREADS':'2'},
        testCases=[ 
            CudaTestCase(CudaError.NO_RACE),
        ]),
    CudaRaceTestProgram("racey/implicit_intra_warp_sync.cu",
        macros={'SHARED':None,'WW': None,'BLOCKS':'1','THREADS':'2'},
        testCases=[ 
            CudaTestCase(CudaError.NO_RACE),
        ]),
    CudaRaceTestProgram("racey/two_streams.cu",
        macros={'RW':None},
        testCases=[ 
            CudaTestCase([CudaError.GLB_RAW,CudaError.GLB_WAR]),
        ]),
    CudaRaceTestProgram("racey/two_streams.cu",
        macros={'WW':None},
        testCases=[ 
            CudaTestCase(CudaError.GLB_WAW),
        ]),
    CudaRaceTestProgram("racey/two_streams.cu",
        macros={'RW':None,'DEVICE_SYNC':None},
        testCases=[ 
            CudaTestCase(CudaError.NO_RACE),
        ]),
    CudaRaceTestProgram("racey/two_streams.cu",
        macros={'WW':None,'DEVICE_SYNC':None},
        testCases=[ 
            CudaTestCase(CudaError.NO_RACE),
        ]),
    CudaRaceTestProgram("racey/two_streams.cu",
        macros={'RW':None,'EVENT_SYNC':None},
        testCases=[ 
            CudaTestCase(CudaError.NO_RACE),
        ]),
    CudaRaceTestProgram("racey/two_streams.cu",
        macros={'WW':None,'EVENT_SYNC':None},
        testCases=[ 
            CudaTestCase(CudaError.NO_RACE),
        ]),
    CudaRaceTestProgram("racey/two_streams.cu",
        macros={'RW':None,'STREAM_SYNC':None},
        testCases=[ 
            CudaTestCase(CudaError.NO_RACE),
        ]),
    CudaRaceTestProgram("racey/two_streams.cu",
        macros={'WW':None,'STREAM_SYNC':None},
        testCases=[ 
            CudaTestCase(CudaError.NO_RACE),
        ]),
    CudaRaceTestProgram("racey/two_streams.cu",
        macros={'RW':None,'STREAM_EVENT_SYNC':None},
        testCases=[ 
            CudaTestCase(CudaError.NO_RACE),
        ]),
    CudaRaceTestProgram("racey/two_streams.cu",
        macros={'WW':None,'STREAM_EVENT_SYNC':None},
        testCases=[ 
            CudaTestCase(CudaError.NO_RACE),
        ]),
    CudaRaceTestProgram("racey/two_streams.cu",
        macros={'RW':None,'STREAM_EVENT_SYNC_NOOP':None},
        testCases=[ 
            CudaTestCase([CudaError.GLB_RAW,CudaError.GLB_WAR]),
        ]),
    CudaRaceTestProgram("racey/two_streams.cu",
        macros={'WW':None,'STREAM_EVENT_SYNC_NOOP':None},
        testCases=[ 
            CudaTestCase(CudaError.GLB_WAW),
        ]),
    CudaRaceTestProgram("racey/warp_lock.cu",
        macros={'GLOBAL':None,'BLOCKS':'1','THREADS':'33'},
        testCases=[ 
            CudaTestCase(CudaError.NO_RACE),
        ]),
    CudaRaceTestProgram("racey/warp_lock.cu",
        macros={'SHARED':None,'BLOCKS':'1','THREADS':'33'},
        testCases=[ 
            CudaTestCase(CudaError.NO_RACE),
        ]),
    CudaRaceTestProgram("racey/warp_lock.cu",
        macros={'GLOBAL':None,'BLOCKS':'2','THREADS':'1'},
        testCases=[ 
            CudaTestCase(CudaError.NO_RACE),
        ]),
    CudaRaceTestProgram("racey/warp_lock.cu",
        macros={'SHARED':None,'BLOCKS':'2','THREADS':'1'},
        testCases=[ 
            CudaTestCase(CudaError.NO_RACE),
        ]),
    CudaRaceTestProgram("racey/warp_lock.cu",
        macros={'GLOBAL':None,'NO_VOLATILE':None,'BLOCKS':'1','THREADS':'33'},
        testCases=[ 
            CudaTestCase(CudaError.GLB_WAW),
        ]),
    CudaRaceTestProgram("racey/warp_lock.cu",
        macros={'SHARED':None,'NO_VOLATILE':None,'BLOCKS':'1','THREADS':'33'},
        testCases=[ 
            CudaTestCase(CudaError.SHR_WAW),
        ]),
    CudaRaceTestProgram("racey/warp_lock.cu",
        macros={'GLOBAL':None,'NO_VOLATILE':None,'BLOCKS':'2','THREADS':'1'},
        testCases=[ 
            CudaTestCase(CudaError.GLB_WAW),
        ]),
    CudaRaceTestProgram("racey/warp_lock.cu",
        macros={'SHARED':None,'NO_VOLATILE':None,'BLOCKS':'2','THREADS':'1'},
        testCases=[ 
            CudaTestCase(CudaError.SHR_WAW),
        ]),
    CudaRaceTestProgram("racey/warp_lock.cu",
        macros={'GLOBAL':None,'NO_LOCK_FENCE':None,'BLOCKS':'1','THREADS':'33'},
        testCases=[ 
            CudaTestCase(CudaError.GLB_WAW),
        ]),
    CudaRaceTestProgram("racey/warp_lock.cu",
        macros={'SHARED':None,'NO_LOCK_FENCE':None,'BLOCKS':'1','THREADS':'33'},
        testCases=[ 
            CudaTestCase(CudaError.SHR_WAW),
        ]),
    CudaRaceTestProgram("racey/warp_lock.cu",
        macros={'GLOBAL':None,'NO_LOCK_FENCE':None,'BLOCKS':'2','THREADS':'1'},
        testCases=[ 
            CudaTestCase(CudaError.GLB_WAW),
        ]),
    CudaRaceTestProgram("racey/warp_lock.cu",
        macros={'SHARED':None,'NO_LOCK_FENCE':None,'BLOCKS':'2','THREADS':'1'},
        testCases=[ 
            CudaTestCase(CudaError.SHR_WAW),
        ]),
    CudaRaceTestProgram("racey/warp_lock.cu",
        macros={'GLOBAL':None,'NO_UNLOCK_FENCE':None,'BLOCKS':'1','THREADS':'33'},
        testCases=[ 
            CudaTestCase(CudaError.GLB_WAW),
        ]),
    CudaRaceTestProgram("racey/warp_lock.cu",
        macros={'SHARED':None,'NO_UNLOCK_FENCE':None,'BLOCKS':'1','THREADS':'33'},
        testCases=[ 
            CudaTestCase(CudaError.SHR_WAW),
        ]),
    CudaRaceTestProgram("racey/warp_lock.cu",
        macros={'GLOBAL':None,'NO_UNLOCK_FENCE':None,'BLOCKS':'2','THREADS':'1'},
        testCases=[ 
            CudaTestCase(CudaError.GLB_WAW),
        ]),
    CudaRaceTestProgram("racey/warp_lock.cu",
        macros={'SHARED':None,'NO_UNLOCK_FENCE':None,'BLOCKS':'2','THREADS':'1'},
        testCases=[ 
            CudaTestCase(CudaError.SHR_WAW),
        ]),
    CudaRaceTestProgram("racey/warp_lock.cu",
        macros={'GLOBAL':None,'NO_LOCK_FENCE':None,'NO_UNLOCK_FENCE':None,'BLOCKS':'1','THREADS':'33'},
        testCases=[ 
            CudaTestCase(CudaError.GLB_WAW),
        ]),
    CudaRaceTestProgram("racey/warp_lock.cu",
        macros={'SHARED':None,'NO_LOCK_FENCE':None,'NO_UNLOCK_FENCE':None,'BLOCKS':'1','THREADS':'33'},
        testCases=[ 
            CudaTestCase(CudaError.SHR_WAW),
        ]),
    CudaRaceTestProgram("racey/warp_lock.cu",
        macros={'GLOBAL':None,'NO_LOCK_FENCE':None,'NO_UNLOCK_FENCE':None,'BLOCKS':'2','THREADS':'1'},
        testCases=[ 
            CudaTestCase(CudaError.GLB_WAW),
        ]),
    CudaRaceTestProgram("racey/warp_lock.cu",
        macros={'SHARED':None,'NO_LOCK_FENCE':None,'NO_UNLOCK_FENCE':None,'BLOCKS':'2','THREADS':'1'},
        testCases=[ 
            CudaTestCase(CudaError.SHR_WAW),
        ]),
]
